name: liveness_detection
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.1
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.8.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.7
  freezed: ^2.3.4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.0
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.3
  injectable: ^2.4.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  video_player: ^2.9.5
  webview_flutter: ^4.10.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

    - family: FamiljenGrotesk
      fonts:
        - asset: assets/fonts/FamiljenGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/FamiljenGrotesk-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/src/presentation/core/gen/
  line_length: 80

  assets:
    outputs:
      package_parameter_enabled: true # <- Add this line.

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

module:
  androidX: true
  androidPackage: com.example.liveness_detection
  iosBundleIdentifier: com.example.livenessDetection
